/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.ganadodietas;

import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.JLabel;

/**
 *
 * @author Usuario
 */
public class InterfazControl extends javax.swing.JFrame {

    /**
     * Creates new form InterfazControl
     */
    public InterfazControl() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        DietasLabel = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        ExitLabel = new javax.swing.JLabel();
        GranjasLabel = new javax.swing.JLabel();
        ReferenciaLabel = new javax.swing.JLabel();
        InformesLabel = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        CambioP = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(163, 34, 85));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Goudy Old Style", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("ADMISTRACION GRANJAS");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 30, 160, -1));

        DietasLabel.setBackground(new java.awt.Color(163, 34, 85));
        DietasLabel.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 12)); // NOI18N
        DietasLabel.setForeground(new java.awt.Color(255, 255, 255));
        DietasLabel.setText("> Adminstracion Dietas");
        DietasLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        DietasLabel.setNextFocusableComponent(DietasLabel);
        DietasLabel.setOpaque(true);
        DietasLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                DietasLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                DietasLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                DietasLabelMouseExited(evt);
            }
        });
        jPanel2.add(DietasLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 150, 31));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 50, 154, 18));

        ExitLabel.setBackground(new java.awt.Color(107, 22, 55));
        ExitLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        ExitLabel.setForeground(new java.awt.Color(255, 255, 255));
        ExitLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ExitLabel.setText("EXIT");
        ExitLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ExitLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ExitLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ExitLabelMouseExited(evt);
            }
        });
        jPanel2.add(ExitLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 520, 60, 30));

        GranjasLabel.setBackground(new java.awt.Color(163, 34, 85));
        GranjasLabel.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 12)); // NOI18N
        GranjasLabel.setForeground(new java.awt.Color(255, 255, 255));
        GranjasLabel.setText("> Administracion Granjas");
        GranjasLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        GranjasLabel.setOpaque(true);
        GranjasLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GranjasLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                GranjasLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                GranjasLabelMouseExited(evt);
            }
        });
        jPanel2.add(GranjasLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 130, 150, 30));

        ReferenciaLabel.setBackground(new java.awt.Color(163, 34, 85));
        ReferenciaLabel.setFont(new java.awt.Font("Microsoft JhengHei UI Light", 1, 12)); // NOI18N
        ReferenciaLabel.setForeground(new java.awt.Color(255, 255, 255));
        ReferenciaLabel.setText(">Tablas de Referencia");
        ReferenciaLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ReferenciaLabel.setOpaque(true);
        ReferenciaLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ReferenciaLabelMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ReferenciaLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ReferenciaLabelMouseExited(evt);
            }
        });
        jPanel2.add(ReferenciaLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, 150, 30));

        InformesLabel.setBackground(new java.awt.Color(163, 34, 85));
        InformesLabel.setFont(new java.awt.Font("Microsoft YaHei UI Light", 1, 12)); // NOI18N
        InformesLabel.setForeground(new java.awt.Color(255, 255, 255));
        InformesLabel.setText("> Informes");
        InformesLabel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        InformesLabel.setOpaque(true);
        InformesLabel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                InformesLabelMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                InformesLabelMouseExited(evt);
            }
        });
        jPanel2.add(InformesLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 150, 30));

        bg.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 180, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 570, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 60, Short.MAX_VALUE)
        );

        bg.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 0, 570, 60));

        javax.swing.GroupLayout CambioPLayout = new javax.swing.GroupLayout(CambioP);
        CambioP.setLayout(CambioPLayout);
        CambioPLayout.setHorizontalGroup(
            CambioPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 560, Short.MAX_VALUE)
        );
        CambioPLayout.setVerticalGroup(
            CambioPLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 540, Short.MAX_VALUE)
        );

        bg.add(CambioP, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 60, 560, 540));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void GranjasLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GranjasLabelMouseEntered
        // TODO add your handling code here:
        GranjasLabel.setBackground(new java.awt.Color(107, 22, 55));


    }//GEN-LAST:event_GranjasLabelMouseEntered

    private void InformesLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InformesLabelMouseEntered
        // TODO add your handling code here:
        InformesLabel.setBackground(new java.awt.Color(107, 22, 55));

    }//GEN-LAST:event_InformesLabelMouseEntered

    private void ExitLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitLabelMouseEntered
        // TODO add your handling code here:

        ExitLabel.setBackground(null);
    }//GEN-LAST:event_ExitLabelMouseEntered

    private void DietasLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DietasLabelMouseEntered
        // TODO add your handling code here:
        DietasLabel.setBackground(new java.awt.Color(107, 22, 55));
    }//GEN-LAST:event_DietasLabelMouseEntered

    private void DietasLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DietasLabelMouseExited
        // TODO add your handling code here:
        DietasLabel.setBackground(null);

    }//GEN-LAST:event_DietasLabelMouseExited

    private void GranjasLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GranjasLabelMouseExited
        // TODO add your handling code here:
        GranjasLabel.setBackground(null);

    }//GEN-LAST:event_GranjasLabelMouseExited

    private void ReferenciaLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReferenciaLabelMouseExited
        // TODO add your handling code here:
        ReferenciaLabel.setBackground(null);

    }//GEN-LAST:event_ReferenciaLabelMouseExited

    private void InformesLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_InformesLabelMouseExited
        // TODO add your handling code here:
        InformesLabel.setBackground(null);

    }//GEN-LAST:event_InformesLabelMouseExited

    private void ReferenciaLabelMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReferenciaLabelMouseEntered
        // TODO add your handling code here:
        ReferenciaLabel.setBackground(new java.awt.Color(107, 22, 55));

    }//GEN-LAST:event_ReferenciaLabelMouseEntered

    private void ExitLabelMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitLabelMouseExited
        // TODO add your handling code here:
        ExitLabel.setBackground(new java.awt.Color(107, 22, 55));
    }//GEN-LAST:event_ExitLabelMouseExited

    private void DietasLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_DietasLabelMouseClicked
        // TODO add your handling code here:

        MantenimientoT mantenimientoT = new MantenimientoT();
        mantenimientoT.setVisible(true);
        mantenimientoT.setSize(1080, 820);
        mantenimientoT.setLocation(50, 0);
        CambioP.removeAll();
        CambioP.add(mantenimientoT, BorderLayout.CENTER);
        CambioP.revalidate();
        CambioP.repaint();

    }//GEN-LAST:event_DietasLabelMouseClicked

    private void ReferenciaLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ReferenciaLabelMouseClicked
        // TODO add your handling code here:
        InterfazD interfaceD = new InterfazD();
        interfaceD.setVisible(true);
        interfaceD.setSize(1080, 820);
        interfaceD.setLocation(50, 0);
        CambioP.removeAll();
        CambioP.add(interfaceD, BorderLayout.CENTER);
        CambioP.revalidate();
        CambioP.repaint();
    }//GEN-LAST:event_ReferenciaLabelMouseClicked

    private void GranjasLabelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GranjasLabelMouseClicked
        // TODO add your handling code here:
        MantenimientoT1 mantenimientoT1 = new MantenimientoT1();
        mantenimientoT1.setVisible(true);
        mantenimientoT1.setSize(1080, 820);
        mantenimientoT1.setLocation(50, 0);
        CambioP.removeAll();
        CambioP.add(mantenimientoT1, BorderLayout.CENTER);
        CambioP.revalidate();
        CambioP.repaint();
    }//GEN-LAST:event_GranjasLabelMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(InterfazControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(InterfazControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(InterfazControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(InterfazControl.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new InterfazControl().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel CambioP;
    private javax.swing.JLabel DietasLabel;
    private javax.swing.JLabel ExitLabel;
    private javax.swing.JLabel GranjasLabel;
    private javax.swing.JLabel InformesLabel;
    private javax.swing.JLabel ReferenciaLabel;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
