/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.ganadodietas;

import static com.mycompany.ganadodietas.MantenimientoTabla.tablaSelec;
import java.beans.JavaBean;

/**
 *
 * @author Usuario
 */
public class MantenimientoT extends javax.swing.JPanel {

    /**
     * Creates new form MantenimientoT
     */
    public static int flag = 0;
    // VALOR DEFAULT DE LA TABLA A MOSTRAR
    public static String tablaSelec = "ALIMENTO";

    public MantenimientoT() {
        initComponents();
        CTabla tabla = new CTabla();
        textEstReg.setEnabled(false);
        txtId.setEnabled(false);
        tabla.Mostrar(tablaQ, tablaSelec);
        CConection conexion = new CConection();
        conexion.estableceConexion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtId = new javax.swing.JTextField();
        textEstReg = new javax.swing.JTextField();
        borrar = new javax.swing.JButton();
        crear = new javax.swing.JButton();
        modificar = new javax.swing.JButton();
        btnInac = new javax.swing.JButton();
        btnReact = new javax.swing.JButton();
        btnActu = new javax.swing.JButton();
        BtnCancel = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        BtnDetalles = new javax.swing.JButton();
        DesJText = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaQ = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        TFlag = new javax.swing.JTextField();

        setEnabled(false);
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setText("Código:");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(78, 20, -1, -1));

        jLabel5.setText("Estado de Registro:");
        jPanel2.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 110, -1));

        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel2.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(138, 17, 163, -1));

        textEstReg.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textEstRegActionPerformed(evt);
            }
        });
        jPanel2.add(textEstReg, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 40, -1));

        borrar.setText("Eliminar");
        borrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                borrarActionPerformed(evt);
            }
        });
        jPanel2.add(borrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 131, 87, -1));

        crear.setText("Adicionar");
        crear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                crearActionPerformed(evt);
            }
        });
        jPanel2.add(crear, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 131, -1, -1));

        modificar.setText("Modificar");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        jPanel2.add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 131, -1, -1));

        btnInac.setText("Inactivar");
        btnInac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInacActionPerformed(evt);
            }
        });
        jPanel2.add(btnInac, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 172, 81, -1));

        btnReact.setText("Reactivar");
        btnReact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnReactActionPerformed(evt);
            }
        });
        jPanel2.add(btnReact, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 172, 81, -1));

        btnActu.setText("Actualizar");
        btnActu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActuActionPerformed(evt);
            }
        });
        jPanel2.add(btnActu, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 172, 87, -1));

        BtnCancel.setText("Cancelar");
        BtnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelActionPerformed(evt);
            }
        });
        jPanel2.add(BtnCancel, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 131, -1, -1));

        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });
        jPanel2.add(BtnSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(273, 172, 76, -1));

        jLabel1.setText("Datos:");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 0, -1, -1));

        BtnDetalles.setText("Detalles");
        BtnDetalles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnDetallesActionPerformed(evt);
            }
        });
        jPanel2.add(BtnDetalles, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 80, 120, -1));

        DesJText.setEditable(false);
        DesJText.setBorder(null);
        DesJText.setEnabled(false);
        jPanel2.add(DesJText, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, 280, -1));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 270, -1, -1));

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tablaQ.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tablaQ.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_INTERVAL_SELECTION);
        tablaQ.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaQMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                tablaQMousePressed(evt);
            }
        });
        tablaQ.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                tablaQComponentShown(evt);
            }
        });
        jScrollPane1.setViewportView(tablaQ);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 360, 210));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 50, -1, 210));

        jLabel2.setText("Tabla:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 16, -1, 30));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "ALIMENTO", "ALIMENTO DIETA TOMA", "NUTRIENTE", "NUTRIENTE ALIMENTO", "FECHA INICIO ", "DIETA", "DIETA ANIMAL FECHA INICIO", "ANIMAL", "ANIMAL NUTRIENTE" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 20, -1, -1));

        TFlag.setText("0");
        TFlag.setEnabled(false);
        TFlag.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TFlagActionPerformed(evt);
            }
        });
        jPanel1.add(TFlag, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 480, 40, -1));

        add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void textEstRegActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textEstRegActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textEstRegActionPerformed

    private void borrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_borrarActionPerformed
        int respuesta = javax.swing.JOptionPane.showConfirmDialog(null, "¿Está seguro de que desea eliminar este registro?", "Confirmar eliminación", javax.swing.JOptionPane.YES_NO_OPTION);
        CTabla tabla = new CTabla();

        if (respuesta == javax.swing.JOptionPane.YES_OPTION) {
            flag = 3;
            textEstReg.setText("*");
            tabla.Eliminar(tablaSelec, txtId, txtId, textEstReg, TFlag);
            TFlag.setText("0");

            inactivar();
            // Aquí puedes agregar el código para eliminar el registro de la base de datos
            javax.swing.JOptionPane.showMessageDialog(null, "El registro ha sido marcado para eliminación.");
            tabla.Mostrar(tablaQ, tablaSelec);

        } else {
            // Acción cancelada, no hacer nada
            javax.swing.JOptionPane.showMessageDialog(null, "La acción de eliminación ha sido cancelada.");

        }
        ActivarF();

        Limpiar();
        inactivar();
    }//GEN-LAST:event_borrarActionPerformed

    private void crearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_crearActionPerformed

        flag = 1;
        TFlag.setText("1");
        textEstReg.setEnabled(false);
        txtId.setEnabled(true);
        txtId.setText("");
        textEstReg.setText("A");
        btnInac.setEnabled(false);
        btnReact.setEnabled(false);
        borrar.setEnabled(false);
        modificar.setEnabled(false);
    }//GEN-LAST:event_crearActionPerformed

    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        flag = 2;

        btnInac.setEnabled(false);
        btnReact.setEnabled(false);
        borrar.setEnabled(false);
        crear.setEnabled(false);
    }//GEN-LAST:event_modificarActionPerformed

    private void btnInacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInacActionPerformed
        flag = 5;

        textEstReg.setText("I");
        CTabla tabla = new CTabla();
        tabla.Inactivar(tablaSelec, txtId, txtId, textEstReg, TFlag);
        ActivarF();

        TFlag.setText("0");
        Limpiar();
        inactivar();
    }//GEN-LAST:event_btnInacActionPerformed

    private void btnReactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnReactActionPerformed
        flag = 4;

        textEstReg.setText("A");
        CTabla tabla = new CTabla();
        tabla.Reactivar(tablaSelec, txtId, txtId, textEstReg, TFlag);
        tabla.Mostrar(tablaQ, tablaSelec);
        TFlag.setText("0");
        Limpiar();
        inactivar();
        ActivarF();
    }//GEN-LAST:event_btnReactActionPerformed

    private void btnActuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActuActionPerformed

        CTabla tabla = new CTabla();
        // int 1 = crear, 2 = editar, 3 = eliminar, 4 = reactivar, 5 = inactivar , 6 = cancelar
        switch (flag) {
            case 1:
                tabla.Insertar(tablaSelec, txtId, txtId, textEstReg, TFlag);
                inactivar();
                TFlag.setText("0");
                inactivar();
                ActivarF();
                Limpiar();
                break;
            case 2:
                tabla.Modificar(tablaSelec, txtId, txtId, textEstReg, TFlag);
                TFlag.setText("0");
                inactivar();
                ActivarF();
                Limpiar();
                break;
            case 3:
                tabla.Eliminar(tablaSelec, txtId, txtId, textEstReg, TFlag);
                inactivar();
                break;
            case 4:
                tabla.Reactivar(tablaSelec, txtId, txtId, textEstReg, TFlag);
                inactivar();
                break;
            case 5:
                tabla.Inactivar(tablaSelec, txtId, txtId, textEstReg, TFlag);
                inactivar();
                break;
            case 6:
                inactivar();
                break;
        }
        tabla.Mostrar(tablaQ, tablaSelec);
    }//GEN-LAST:event_btnActuActionPerformed

    private void BtnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelActionPerformed
        flag = 6;
        Limpiar();
        inactivar();
        ActivarF();
    }//GEN-LAST:event_BtnCancelActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed

    }//GEN-LAST:event_BtnSalirActionPerformed

    private void BtnDetallesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnDetallesActionPerformed
        // TODO add your handling code here:
        javax.swing.JTable table = tablaQ; // Reference to your JTable

        int selectedRow = tablaQ.getSelectedRow();
        if (selectedRow == -1) {
            javax.swing.JOptionPane.showMessageDialog(null, "Seleccione una fila primero.");
            return;
        }

        // Get data from the selected row
        int columnCount = tablaQ.getColumnCount();
        Object[] rowData = new Object[columnCount];
        String[] columnNames = new String[columnCount];
        for (int i = 0; i < columnCount; i++) {

            rowData[i] = tablaQ.getValueAt(selectedRow, i);
            columnNames[i] = tablaQ.getColumnName(i);

        }
        System.out.println(rowData.toString());
        System.out.println(columnNames.toString());

        // Create and show the detail frame
        // Create and show the detail frame
        DetailFrame detailFrame = new DetailFrame(rowData, columnNames, new DetailFrame.DetailFrameCallback() {
            @Override
            public void onDetailGenerated(String desc) {
                DesJText.setText(desc);
            }
        });
        detailFrame.setVisible(true);
    }//GEN-LAST:event_BtnDetallesActionPerformed

    private void tablaQMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaQMouseClicked
        CTabla tabla = new CTabla();

        if (textEstReg.getText().equals("*")) {
            javax.swing.JOptionPane.showMessageDialog(null, "La acción no es posible el elemento fue eliminado");
            Limpiar();
            inactivar();
            TFlag.setText("0");
            ActivarF();
        } else {

            tabla.Seleccionar(tablaQ, txtId, txtId, textEstReg, TFlag);
            ActivarT2();
        }
    }//GEN-LAST:event_tablaQMouseClicked

    private void tablaQMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaQMousePressed
        // TODO add your handling code here:
        CTabla tabla = new CTabla();
        if (textEstReg.getText().equals("*")) {
            javax.swing.JOptionPane.showMessageDialog(null, "La acción no es posible el elemento fue eliminado");
            Limpiar();
            TFlag.setText("0");

            inactivar();
        } else {

            tabla.Seleccionar(tablaQ, txtId, txtId, textEstReg, TFlag);

        }
    }//GEN-LAST:event_tablaQMousePressed

    private void tablaQComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_tablaQComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_tablaQComponentShown

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        String elmSel = (String) jComboBox1.getSelectedItem();
        tablaSelec = elmSel;
        CTabla tabla = new CTabla();
        tabla.Mostrar(tablaQ, tablaSelec);
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void TFlagActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TFlagActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TFlagActionPerformed
    private void ActivarT() {
        btnInac.setEnabled(true);
        btnReact.setEnabled(true);
        borrar.setEnabled(true);
        modificar.setEnabled(true);
        crear.setEnabled(true);

    }

    private void ActivarT2() {
        btnInac.setEnabled(true);
        btnReact.setEnabled(true);
        borrar.setEnabled(true);
        modificar.setEnabled(true);

    }

    private void ActivarF() {
        btnInac.setEnabled(false);
        btnReact.setEnabled(false);
        borrar.setEnabled(false);
        modificar.setEnabled(false);
        crear.setEnabled(true);

    }

    private void Limpiar() {
        txtId.setText("");
        textEstReg.setText("");

    }

    private void inactivar() {
        textEstReg.setEnabled(false);
        txtId.setEnabled(false);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancel;
    private javax.swing.JButton BtnDetalles;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JTextField DesJText;
    private javax.swing.JTextField TFlag;
    private javax.swing.JButton borrar;
    private javax.swing.JButton btnActu;
    private javax.swing.JButton btnInac;
    private javax.swing.JButton btnReact;
    private javax.swing.JButton crear;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton modificar;
    private javax.swing.JTable tablaQ;
    private javax.swing.JTextField textEstReg;
    private javax.swing.JTextField txtId;
    // End of variables declaration//GEN-END:variables
}
