# Generated by Django 5.0.6 on 2024-06-11 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('test', '0002_delete_authgroup_delete_authgrouppermissions_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pais',
            options={},
        ),
    ]
